#GRUPOS

# 1:MORADIA, 2:SAÚDE, 3:ALIMENTAÇÃO, 4:EDUCAÇÃO, 5:TRANSPORTE, 6:GASTOS PESSOAIS, 7:DIVERSÃO

#SUBGRUPOS
#1.X: ALUGUEL, LUZ, ÁGUA, INTERNET, CELULAR, AQUISIÇÕES
#2.X: REMÉDIOS, HOSPITAL/VET, ACADEMIA
#3.X: MERCADO, ALMOÇO, JANTAR
#4.X: CURSOS, TREINAMENTOS, INVESTIMENTO EM MATERIAL
#5.X: COMBUSTÍVEL, MANUTENÇÃO PREVENTIVA, MANUTENÇÃO CORRETIVA
#6.X: ROUPAS, CABELEREIRO,  COSMÉTICOS, PRESENTES
#7.X: SHOPPING, BARZINHO, RESTAURANTE, VIAGEM

#SUBIR PROJETO NO GIT, VERSIONAMENTO
#DOCKER

#